export const enum ErrorCode {
  EXPECTED,
  EXPECTED_BUT_GOT,
  NO_TRAVERSER_IS_FOUND,
  PARSER_ERROR,
  SYMBOL_ALREADY_DECLARED,
  SYMBOL_IS_NOT_DECLARED,
  UNEXPECTED,
  UNRECOGNIZED_CHARACTER,
  UNTERMINATED_STRING_LITERAL,
}
