export const enum BinaryOperator {
  EQUAL = '==',
  NOT_EQUAL = '!=',
  STRICT_EQUAL = '===',
  NOT_STRICT_EQUAL = '!==',
  LESS_THAN = '<',
  LESS_THAN_OR_EQUAL = '<=',
  GREATER_THAN = '>',
  GREATER_THAN_OR_EQUAL = '>=',
  BITWISE_SHIFT_LEFT = '<<',
  BITWISE_SHIFT_RIGHT = '>>',
  BITWISE_SHIFT_RIGHT_ZERO = '>>>',
  PLUS = '+',
  MINUS = '-',
  MULTIPLY = '*',
  EXPONENTIATION = '**',
  DIVIDE = '/',
  MODULUS = '%',
  BITWISE_AND = '&',
  BITWISE_OR = '|',
  BITWISE_XOR = '^',
  IN = 'in',
  INSTANCE_OF = 'instanceof',
}
