import { Token } from "../token/Token";
import { TokenType } from "../token/TokenType";

export const PUNCTUATION = new Map<string, Token>([
  ["!", new Token(TokenType.LOGICAL_NOT, "!")],
  ["!=", new Token(TokenType.NOT_EQUAL, "!=")],
  ["!==", new Token(TokenType.NOT_STRICT_EQUAL, "!==")],
  ["%", new Token(TokenType.MODULUS, "%")],
  ["%=", new Token(TokenType.MODULUS_ASSIGN, "%=")],
  ["&", new Token(TokenType.BITWISE_AND, "&")],
  ["&&", new Token(TokenType.LOGICAL_AND, "&&")],
  ["&=", new Token(TokenType.BITWISE_AND_ASSIGN, "&=")],
  ["(", new Token(TokenType.LEFT_PARENTHESIS, "(")],
  [")", new Token(TokenType.RIGHT_PARENTHESIS, ")")],
  ["*", new Token(TokenType.MULTIPLY, "*")],
  ["**", new Token(TokenType.EXPONENTIATION, "**")],
  ["**=", new Token(TokenType.EXPONENTIATION_ASSIGN, "**=")],
  ["*=", new Token(TokenType.MULTIPLY_ASSIGN, "*=")],
  ["+", new Token(TokenType.PLUS, "+")],
  ["++", new Token(TokenType.PLUS_PLUS, "++")],
  ["+=", new Token(TokenType.PLUS_ASSIGN, "+=")],
  [",", new Token(TokenType.COMMA, ",")],
  ["-", new Token(TokenType.MINUS, "-")],
  ["--", new Token(TokenType.MINUS_MINUS, "--")],
  ["-=", new Token(TokenType.MINUS_ASSIGN, "-=")],
  [".", new Token(TokenType.DOT, ".")],
  ["...", new Token(TokenType.ELLIPSIS, "...")],
  ["/", new Token(TokenType.DIVIDE, "/")],
  ["/=", new Token(TokenType.DIVIDE_ASSIGN, "/=")],
  [":", new Token(TokenType.COLON, ":")],
  [";", new Token(TokenType.SEMICOLON, ";")],
  ["<", new Token(TokenType.LESS_THAN, "<")],
  ["<<", new Token(TokenType.BITWISE_SHIFT_TO_LEFT, "<<")],
  ["<<=", new Token(TokenType.BITWISE_SHIFT_TO_LEFT_ASSIGN, "<<=")],
  ["<=", new Token(TokenType.LESS_THAN_OR_EQUAL, "<=")],
  ["=", new Token(TokenType.ASSIGN, "=")],
  ["==", new Token(TokenType.EQUAL, "==")],
  ["===", new Token(TokenType.STRICT_EQUAL, "===")],
  ["=>", new Token(TokenType.ARROW, "=>")],
  [">", new Token(TokenType.GREATER_THAN, ">")],
  [">=", new Token(TokenType.GREATER_THAN_OR_EQUAL, ">=")],
  [">>", new Token(TokenType.BITWISE_SHIFT_TO_RIGHT, ">>")],
  [">>=", new Token(TokenType.BITWISE_SHIFT_TO_RIGHT_ASSIGN, ">>=")],
  [">>>", new Token(TokenType.BITWISE_LOGICAL_SHIFT_TO_RIGHT, ">>>")],
  [">>>=", new Token(TokenType.BITWISE_LOGICAL_SHIFT_TO_RIGHT_ASSIGN, ">>>=")],
  ["?", new Token(TokenType.QUESTION_MARK, "?")],
  ["[", new Token(TokenType.LEFT_SQUARE_BRACKETS, "[")],
  ["]", new Token(TokenType.RIGHT_SQUARE_BRACKETS, "]")],
  ["^", new Token(TokenType.BITWISE_XOR, "^")],
  ["^=", new Token(TokenType.BITWISE_XOR_ASSIGN, "^=")],
  ["{", new Token(TokenType.LEFT_CURLY_BRACES, "{")],
  ["|", new Token(TokenType.BITWISE_OR, "|")],
  ["|=", new Token(TokenType.BITWISE_OR_ASSIGN, "|=")],
  ["||", new Token(TokenType.LOGICAL_OR, "||")],
  ["}", new Token(TokenType.RIGHT_CURLY_BRACES, "}")],
  ["~", new Token(TokenType.BITWISE_NOT, "~")],
]);
